config/routes.rb
Rails.application.routes.draw do
  root 'modelnames#index'
  resources :modelnames
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/modelname.rb
class Modelname < ApplicationRecord
    validates :fieldone , length: { maximum: 32 } , presence: true
    validates :fieldtwo , length: { maximum: 256} , presence: true
    validates :fieldthree , length: { maximum: 9} , presence: true
    validates :age , length: { maximum: 3} , presence: false
    validates :lot,length:{maximum:99},presence:false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/modelnames_controller.rb
class ModelnamesController < ApplicationController
  before_action :set_modelname, only: [:show, :edit, :update, :destroy]

  # GET /modelnames
  # GET /modelnames.json
  def index
    @modelnames = Modelname.all
  end

  # GET /modelnames/1
  # GET /modelnames/1.json
  def show
  end

  # GET /modelnames/new
  def new
    @modelname = Modelname.new
  end

  # GET /modelnames/1/edit
  def edit
  end

  # POST /modelnames
  # POST /modelnames.json
  def create
    @modelname = Modelname.new(modelname_params)

    respond_to do |format|
      if @modelname.save
        format.html { redirect_to @modelname, notice: 'Modelname was successfully created.' }
        format.json { render :show, status: :created, location: @modelname }
      else
        format.html { render :new }
        format.json { render json: @modelname.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /modelnames/1
  # PATCH/PUT /modelnames/1.json
  def update
    respond_to do |format|
      if @modelname.update(modelname_params)
        format.html { redirect_to @modelname, notice: 'Modelname was successfully updated.' }
        format.json { render :show, status: :ok, location: @modelname }
      else
        format.html { render :edit }
        format.json { render json: @modelname.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /modelnames/1
  # DELETE /modelnames/1.json
  def destroy
    @modelname.destroy
    respond_to do |format|
      format.html { redirect_to modelnames_url, notice: 'Modelname was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_modelname
      @modelname = Modelname.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def modelname_params
      params.require(:modelname).permit(:fieldone, :fieldtwo, :fieldthree, :age, :lot)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/modelnames_helper.rb
module ModelnamesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyBlog3</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/modelnames/_form.html.erb
<%= form_for(modelname) do |f| %>
  <% if modelname.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(modelname.errors.count, "error") %> prohibited this modelname from being saved:</h2>

      <ul>
      <% modelname.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fieldone %>
    <%= f.text_field :fieldone %>
  </div>

  <div class="field">
    <%= f.label :fieldtwo %>
    <%= f.text_area :fieldtwo %>
  </div>

  <div class="field">
    <%= f.label :fieldthree %>
    <%= f.number_field :fieldthree %>
  </div>
  
  <div class="field">
    <%= f.label :age %>
    <%= f.number_field :age %>
  </div>
  
  <div class="field">
    <%= f.label :lot %>
    <%= f.number_field :lot %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/modelnames/edit.html.erb
<h1>Editing Modelname</h1>

<%= render 'form', modelname: @modelname %>

<%= link_to 'Show', @modelname %> |
<%= link_to 'Back', modelnames_path %>

app/views/modelnames/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Modelnames</h1>

<table>
  <thead>
    <tr>
      <th>Fieldone</th>
      <th>Fieldtwo</th>
      <th>Fieldthree</th>
      <th>Age</th>
      <th>Lot</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @modelnames.each do |modelname| %>
      <tr>
        <td><%= modelname.fieldone %></td>
        <td><%= modelname.fieldtwo %></td>
        <td><%= modelname.fieldthree %></td>
        <td><%= modelname.age %></td>
        <td><%= modelname.lot %></td>
        
        <td><%= link_to 'Show', modelname %></td>
        <td><%= link_to 'Edit', edit_modelname_path(modelname) %></td>
        <td><%= link_to 'Destroy', modelname, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Modelname', new_modelname_path %>

app/views/modelnames/new.html.erb
<h1>New Modelname</h1>

<%= render 'form', modelname: @modelname %>

<%= link_to 'Back', modelnames_path %>

app/views/modelnames/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fieldone:</strong>
  <%= @modelname.fieldone %>
</p>

<p>
  <strong>Fieldtwo:</strong>
  <%= @modelname.fieldtwo %>
</p>

<p>
  <strong>Fieldthree:</strong>
  <%= @modelname.fieldthree %>
</p>

<p>
  <strong>Age:</strong>
  <%= @modelname.age %>
</p>

<p>
  <strong>Lot:</strong>
  <%= @modelname.lot %>
</p>

<%= link_to 'Edit', edit_modelname_path(@modelname) %> |
<%= link_to 'Back', modelnames_path %>